### ISSUE TITLE
check_file_exists is not returning as critical even if the file exist on windows

### ISSUE THREAD

**Issue by shaleenageorge** [ncr-devops-platform/nagios-foundation#154]
The check is not returning as critical if the file exist in the path.
See image below for the file and its path

![image](https://user-images.githubusercontent.com/51759977/59464828-19bc9400-8def-11e9-9c10-cd0053637354.png)

**Tried this command:**
command: check_file_exists --pattern 'C:\BootDrv\Aloha\TMP\debout.NoException-15.1.34.2.97-20190604-134206.dmp' --negate

**Getting this error:**
![image](https://user-images.githubusercontent.com/51759977/59464638-9ef37900-8dee-11e9-9d66-38565aa2a06b.png)
Tried this directly on the machine:
![image](https://user-images.githubusercontent.com/51759977/59464701-bfbbce80-8dee-11e9-863a-616bd12bca7b.png)

**Comment by cwjohnston** [comment]
Hi @shaleenageorge, good news! After some testing I've found that the plugin is working as expected on Windows, provided that the value passed to `--pattern` is not single-quoted. In my tests, patterns without quotes or with double-quotes worked as expected, but single quotes were not properly interpreted.

I believe that on Linux systems the single quotes are necessary when specifying globbing patterns because the pattern is otherwise interpreted by the shell instead of being passed along directly to the check plugin. 

Will you please try adjusting your check definition so that there are no quotes around the value provided for the  `--pattern` flag and see if that makes any difference for you?

**Comment by quaggoth** [comment]
Good catch @cwjohnston. I suspected that was the case since in Windows I've always used double-quotes but I don't have a Windows system near me to check on that (all Linux and Chrome OS around here). As you stated, the Windows command prompt requires double-quotes and there's a blurb about it at https://ss64.com/nt/syntax-esc.html.

I am fairly sure if you were using PowerShell, the rule changes and you can use single-quotes to quote a parameter.

**Comment by shaleenageorge** [comment]
Yes, that was it. It works now.
